#!/usr/bin/env php
<?php
// build_index time_bound, split_in_to, my_work
// eg: split works into 4 parts and do the NO.2
//     build_index 1321758152, 4, 1

require_once 'www2-funcs.php';
require_once 'search/lib/helper.php';

bbs_setuser_nologin('SYSOP');

if ($argc != 4) {
    $time_bound  = time();
    $split_in_to = 1;
    $my_work     = 0;
} else {
    $time_bound  = $argv[1];
    $split_in_to = $argv[2];
    $my_work     = $argv[3];
}

$start_time = time();
$all = 0;

$boards = bbs_super_getboards();

// skip to my works
$pieces = count($boards) / $split_in_to;
if ($my_work != $split_in_to - 1) // normal works
    $boards = array_slice($boards, $pieces * $my_work, $pieces);
else // last work
    $boards = array_slice($boards, $pieces * $my_work);

foreach ($boards as $key => &$board) {
    $board_name   = $board['NAME'];
    $board_id     = $board['BID'];

    $xs = new XS(XS_CONF);
    $index = $xs->index;

    $count = 0;
    $total = bbs_countarticles($board_id, 0, 0);

//    printf ('[%s] :           ', $board_name);

    $i = 1;
    $PAGE = 100;
    while ($total > 0) {
        $quit = false;

        if ($i + $PAGE > $total + 1) {
            $quit = true;
            $PAGE = $total - $i + 1;
        }

        $articles = bbs_getarticles($board_name, $i, $PAGE, 0, 0);

        foreach ($articles as $key => &$val) {
            if ($val['POSTTIME'] > $time_bound) continue;

            try {
                xs_import_article($index, $board, $val);
                ++$count;
            } catch(Exception $e) {
                echo 'Error: ', $e->getMessage(), "\n";
            }
        }

        $i += $PAGE;

        echo $board_name, ' ', $i, ' ', (int)($count / $total * 100), "%\n";

//        progress($count / $total, $i);

        if ($quit) break;
    }

    $all += $count;
    printf ("\nTotal: %d, Valid: %d\n", $total, $count);
}

echo 'Done: ', $all, "\n";
echo 'Time: ', time() - $start_time, "\n";
?>
