#!/usr/bin/env php
<?php
require_once 'www2-funcs.php';
require_once 'search/lib/helper.php';

bbs_setuser_nologin('SYSOP');

$xs = new XS(XS_CONF);
$index = $xs->index;

for ($i = getDbNumByYear(TORG); $i <= getDbNumByYear(TNOW); $i++) {
    try {
        $index->setDb('db' . $i);
        $index->clean();
    } catch (Exception $e) {
        echo $i, ' : ', $e->getMessage(), "\n";
    }
}

$boards = bbs_super_getboards();
foreach ($boards as $key => &$board) {
    try {
        $index->setDb('db_private_' . strtolower($board['NAME']));
        $index->clean();
    } catch (Exception $e) {
        echo $board['NAME'], ' : ', $e->getMessage(), "\n";
    }
}

// Push empty data to the db
$index->setDb('db');
$index->clean();
$data = array(
    'id'         => 0,
    'first'      => 0,
    'attachment' => 0,
    'replies'    => 0,
    'mark'       => 0,
    'good'       => 0,
    'title'      => 0,
    'content'    => 0,
    'time'       => 0,
    'author'     => 0,
    'path'       => 0,
    'board'      => 0
);
$doc = new XSDocument;
$doc->setFields($data);
$index->add($doc);
?>
